import type { ArchitectureEdge, ProjectComponent, ProjectMap } from './ProjectMapModels';
import { validateProjectMap } from './ProjectMapValidator';

export interface DeleteComponentResult { map: ProjectMap; removedEdgeIds: string[]; hadRecentActivity: boolean }

export function addComponent(map: ProjectMap, component: ProjectComponent): ProjectMap { return validated({ ...map, components: [...map.components, component] }); }
export function updateComponent(map: ProjectMap, component: ProjectComponent): ProjectMap { if (!map.components.some(item => item.id === component.id)) throw new Error(`Unknown component "${component.id}".`); return validated({ ...map, components: map.components.map(item => item.id === component.id ? component : item) }); }
export function deleteComponent(map: ProjectMap, componentId: string, recentComponentIds: string[] = []): DeleteComponentResult { if (!map.components.some(item => item.id === componentId)) throw new Error(`Unknown component "${componentId}".`); const removed = map.edges.filter(edge => edge.source === componentId || edge.target === componentId); return { map: validated({ ...map, components: map.components.filter(item => item.id !== componentId), edges: map.edges.filter(edge => edge.source !== componentId && edge.target !== componentId) }), removedEdgeIds: removed.map(edge => edge.id), hadRecentActivity: recentComponentIds.includes(componentId) }; }
export function addEdge(map: ProjectMap, edge: ArchitectureEdge): ProjectMap { return validated({ ...map, edges: [...map.edges, edge] }); }
export function updateEdge(map: ProjectMap, edge: ArchitectureEdge): ProjectMap { if (!map.edges.some(item => item.id === edge.id)) throw new Error(`Unknown architecture edge "${edge.id}".`); return validated({ ...map, edges: map.edges.map(item => item.id === edge.id ? edge : item) }); }
export function reverseEdge(map: ProjectMap, edgeId: string): ProjectMap { const edge = map.edges.find(item => item.id === edgeId); if (edge === undefined) throw new Error(`Unknown architecture edge "${edgeId}".`); return updateEdge(map, { ...edge, source: edge.target, target: edge.source }); }
export function deleteEdge(map: ProjectMap, edgeId: string): ProjectMap { if (!map.edges.some(item => item.id === edgeId)) throw new Error(`Unknown architecture edge "${edgeId}".`); return validated({ ...map, edges: map.edges.filter(item => item.id !== edgeId) }); }
export function mapFromSuggestions(projectName: string, suggestions: Array<{ id: string; name: string; type: ProjectComponent['type']; paths: string[] }>): ProjectMap { return validated({ schemaVersion: 1, project: { name: projectName }, components: suggestions.map((item, index) => ({ ...item, position: { x: 120 + (index % 3) * 280, y: 100 + Math.floor(index / 3) * 180 } })), edges: [] }); }
function validated(value: unknown): ProjectMap { const result = validateProjectMap(value); if (result.map === undefined) throw new Error(result.errors.join(' ')); return result.map; }
